In [11]:
import numpy as np
import pickle
import random

# Example input data with days represented by zero-based indices for each district
input_data2 = [
    [1, 2, 5], [2, 4, 6], [1, 3, 5], [1, 3, 5],
    [1, 4, 5], [2, 4, 6], [1, 3, 5], [1, 3, 5],
    [2, 4, 6], [2, 4, 6], [2, 4, 6], [2, 4, 6]
]

# Proportionally split 1000 according to a 12-element array
base_array = np.array([ 43.57303419,  65.53205128,  96.98660256,  76.66292735,  42.92226496,
  94.48630342, 160.81747863, 171.82707265,  77.58852564,  91.11824786,
  75.12809829, 161.76136752])  # Example distribution
proportional_array = (1000 * base_array / base_array.sum()).astype(int)  # Array `p`

# Initialize the result array
result = np.zeros((12, 7, 2), dtype=int)

# Populate the result array based on input_data2 and proportional_array
for i in range(12):  # Loop over each district
    for day_index in input_data2[i]:  # Loop over each specified day for the district
        time_slot = random.choice([0, 1])  # Randomly assign to morning (0) or evening (1)
        result[i][day_index][time_slot] = proportional_array[i] / 3  # Assign the refuse amount

# Save the result array as a pickle file
with open("Real.pkl", "wb") as file:
    pickle.dump(result, file)
print(proportional_array)

print(result)
print("Generated and saved the (12, 7, 2) array to 'result.pkl'")

[ 37  56  83  66  37  81 138 148  66  78  64 139]
[[[ 0  0]
  [ 0 12]
  [12  0]
  [ 0  0]
  [ 0  0]
  [12  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [18  0]
  [ 0  0]
  [18  0]
  [ 0  0]
  [ 0 18]]

 [[ 0  0]
  [ 0 27]
  [ 0  0]
  [ 0 27]
  [ 0  0]
  [27  0]
  [ 0  0]]

 [[ 0  0]
  [ 0 22]
  [ 0  0]
  [ 0 22]
  [ 0  0]
  [ 0 22]
  [ 0  0]]

 [[ 0  0]
  [ 0 12]
  [ 0  0]
  [ 0  0]
  [ 0 12]
  [12  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [27  0]
  [ 0  0]
  [27  0]
  [ 0  0]
  [27  0]]

 [[ 0  0]
  [ 0 46]
  [ 0  0]
  [ 0 46]
  [ 0  0]
  [ 0 46]
  [ 0  0]]

 [[ 0  0]
  [ 0 49]
  [ 0  0]
  [ 0 49]
  [ 0  0]
  [49  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0 22]
  [ 0  0]
  [ 0 22]
  [ 0  0]
  [ 0 22]]

 [[ 0  0]
  [ 0  0]
  [26  0]
  [ 0  0]
  [ 0 26]
  [ 0  0]
  [ 0 26]]

 [[ 0  0]
  [ 0  0]
  [ 0 21]
  [ 0  0]
  [ 0 21]
  [ 0  0]
  [ 0 21]]

 [[ 0  0]
  [ 0  0]
  [46  0]
  [ 0  0]
  [46  0]
  [ 0  0]
  [ 0 46]]]
Generated and saved the (12, 7, 2) array to 'result.pkl'
